ecommerce/cart/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^update/(?P<product_id>\d+)/$', views.index, name='update_line')
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve

from .cart.urls import urlpatterns as cart_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .userprofile.urls import urlpatterns as userprofile_urls


admin.autodiscover()

urlpatterns = [
    url(r'^', include(core_urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cart/', include(cart_urls, namespace='cart')),
    url(r'^checkout/', include(checkout_urls, namespace='checkout')),
    url(r'^order/', include(order_urls, namespace='order')),
    url(r'^products/', include(product_urls, namespace='product')),
    url(r'^profile/', include(userprofile_urls, namespace='profile')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^api/v1/', include('ecommerce.urls_api')),
    url(r'', include('payments.urls'))
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', serve)
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/cart/models.py
from datetime import datetime
from ecommerce.product.models import ProductVariant


class NewCartItem(object):
    def __init__(self, product, quantity, price, data, msg=''):
        self.product = product
        self.quantity = quantity
        self.price = price
        self.data = data
        self.msg = msg

    @property
    def sub_total(self):
        return self.quantity * self.price


class NewCart(object):
    def __init__(self, created_date=None,):
        self.created_date = created_date if created_date else datetime.now()

        self.updated_date = datetime.now()
        self.items = []

    @property
    def total(self):
        total = float(0)
        for item in self.items:
            total += float(item.sub_total)
        return total

    def add_item(self, product, quantity, data, action='increment'):
        # TODO: borrar el item si fue modificado
        try:
            variant = ProductVariant.objects.get(id=product)
        except:
            variant = None

        if variant:
            msg = ''
            # Checkear si otro item con la misma variacion ya reservo stock
            reserved_stock = 0
            for item in self.items:
                if item.product == product:
                    reserved_stock = reserved_stock + item.quantity

            stocked_quantity = variant.get_stock_quantity()
            available_quantity = stocked_quantity - reserved_stock

            if action == 'increment':
                for item in self.items:
                    if item.product == product:
                        if quantity > available_quantity:
                            item.quantity = item.quantity + available_quantity
                            item.msg = 'No hay suficiente stock para este item. Hemos ingresado para este item, el maximo disponible'
                        else:
                            item.quantity = item.quantity + quantity
                        break
                else: # this else belongs to the for loop and it's executed only if break instruction has no been executed.
                    if quantity > available_quantity:
                        new_quantity = available_quantity
                        msg = 'No hay suficiente stock para este item. Hemos ingresado para este item, el maximo disponible'
                    else:
                        new_quantity = quantity
                    if new_quantity > 0:
                        item = NewCartItem(product=product, quantity=new_quantity, price=variant.get_price_per_item(), data=data, msg=msg)
                        item.variant = variant
                        self.items.append(item)

            elif action == 'add':
                if quantity > available_quantity:
                    new_quantity = available_quantity
                    msg = 'No hay suficiente stock para este item. Hemos ingresado para este item, el maximo disponible'
                else:
                    new_quantity = quantity
                if new_quantity > 0:
                    item = NewCartItem(product=product, quantity=new_quantity, price=variant.get_price_per_item(), data=data, msg=msg)
                    item.variant = variant
                    self.items.append(item)
            elif action == 'replace':
                for item in self.items:
                    if item.product == product:
                        if quantity > available_quantity:
                            item.quantity = available_quantity
                            item.msg = 'No hay suficiente stock para este item. Hemos ingresado para este item, el maximo disponible'
                        else:
                            item.quantity = quantity
                        break
                else: # this else belongs to the for loop and it's executed only if break instruction has no been executed.
                    if quantity > available_quantity:
                        new_quantity = available_quantity
                        msg = 'No hay suficiente stock para este item. Hemos ingresado para este item, el maximo disponible'
                    else:
                        new_quantity = quantity
                    if new_quantity > 0:
                        item = NewCartItem(product=product, quantity=new_quantity, price=variant.get_price_per_item(), data=data, msg=msg)
                        item.variant = variant
                        self.items.append(item)

ecommerce/cart/forms.py
from __future__ import unicode_literals

from django import forms
from django.core.exceptions import ObjectDoesNotExist, NON_FIELD_ERRORS
from django.forms.formsets import BaseFormSet, DEFAULT_MAX_NUM
from django.utils.translation import pgettext_lazy, ugettext_lazy
from satchless.item import InsufficientStock


class QuantityField(forms.IntegerField):

    def __init__(self, **kwargs):
        super(QuantityField, self).__init__(min_value=0, max_value=999,
                                            initial=1, **kwargs)


class AddToCartForm(forms.Form):
    """Add-to-cart form

    Allows selection of a product variant and quantity.
    The save method adds it to the cart.
    """
    quantity = QuantityField(label=pgettext_lazy('Form field', 'Quantity'))
    error_messages = {
        'empty-stock': ugettext_lazy(
            'Sorry. This product is currently out of stock.'
        ),
        'variant-does-not-exists': ugettext_lazy(
            'Oops. We could not find that product.'
        ),
        'insufficient-stock': ugettext_lazy(
            'Only %(remaining)d remaining in stock.'
        )
    }

    def __init__(self, *args, **kwargs):
        self.cart = kwargs.pop('cart')
        self.product = kwargs.pop('product')
        super(AddToCartForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = super(AddToCartForm, self).clean()
        quantity = cleaned_data.get('quantity')
        if quantity is None:
            return cleaned_data
        try:
            product_variant = self.get_variant(cleaned_data)
        except ObjectDoesNotExist:
            msg = self.error_messages['variant-does-not-exists']
            self.add_error(NON_FIELD_ERRORS, msg)
        else:
            cart_line = self.cart.get_line(product_variant)
            used_quantity = cart_line.quantity if cart_line else 0
            new_quantity = quantity + used_quantity
            try:
                self.cart.check_quantity(
                    product_variant, new_quantity, None)
            except InsufficientStock as e:
                remaining = e.item.get_stock_quantity() - used_quantity
                if remaining:
                    msg = self.error_messages['insufficient-stock']
                else:
                    msg = self.error_messages['empty-stock']
                self.add_error('quantity', msg % {'remaining': remaining})
        return cleaned_data

    def save(self):
        """Adds the selected product variant and quantity to the cart"""
        product_variant = self.get_variant(self.cleaned_data)
        return self.cart.add(product_variant, self.cleaned_data['quantity'])

    def get_variant(self, cleaned_data):
        raise NotImplementedError()


class ReplaceCartLineForm(AddToCartForm):
    """Replace quantity form

    Similar to AddToCartForm but its save method replaces the quantity.
    """
    def __init__(self, *args, **kwargs):
        super(ReplaceCartLineForm, self).__init__(*args, **kwargs)
        self.cart_line = self.cart.get_line(self.product)
        self.fields['quantity'].widget.attrs = {
            'min': 1, 'max': self.product.get_stock_quantity()}

    def clean_quantity(self):
        quantity = self.cleaned_data['quantity']
        try:
            self.cart.check_quantity(self.product, quantity, None)
        except InsufficientStock as e:
            msg = self.error_messages['insufficient-stock']
            raise forms.ValidationError(msg % {
                'remaining': e.item.get_stock_quantity()})
        return quantity

    def clean(self):
        # explicitly skip parent's implementation
        # pylint: disable=E1003
        return super(AddToCartForm, self).clean()

    def get_variant(self, cleaned_data):
        """In cart formsets product is already the variant we want"""
        return self.product

    def save(self):
        """Replaces the selected product's quantity in cart"""
        product_variant = self.get_variant(self.cleaned_data)
        return self.cart.add(product_variant, self.cleaned_data['quantity'],
                             replace=True)


class ReplaceCartLineFormSet(BaseFormSet):
    absolute_max = 9999
    can_delete = False
    can_order = False
    extra = 0
    form = ReplaceCartLineForm
    max_num = DEFAULT_MAX_NUM
    validate_max = False
    min_num = 0
    validate_min = False

    def __init__(self, *args, **kwargs):
        self.cart = kwargs.pop('cart')
        kwargs['initial'] = [{'quantity': cart_line.get_quantity()}
                             for cart_line in self.cart
                             if cart_line.get_quantity()]
        super(ReplaceCartLineFormSet, self).__init__(*args, **kwargs)

    def _construct_form(self, i, **kwargs):
        kwargs['cart'] = self.cart
        kwargs['product'] = self.cart[i].product
        return super(ReplaceCartLineFormSet, self)._construct_form(i, **kwargs)

    def save(self):
        for form in self.forms:
            form.save()

ecommerce/cart/views.py
from __future__ import unicode_literals
from babeldjango.templatetags.babel import currencyfmt

from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import redirect
from django.template.response import TemplateResponse
from django.utils.translation import ugettext as _

from . import Cart
from .forms import ReplaceCartLineForm
from ..cart.utils import (
    contains_unavailable_products, remove_unavailable_products)


def index(request, product_id=None):
    if product_id is not None:
        product_id = int(product_id)
    cart = Cart.for_session_cart(request.cart, discounts=request.discounts)
    if contains_unavailable_products(cart):
        msg = _('Sorry. We don\'t have that many items in stock. '
                'Quantity was set to maximum available for now.')
        messages.warning(request, msg)
        remove_unavailable_products(cart)
    for line in cart:
        data = None
        if line.product.pk == product_id:
            data = request.POST
        initial = {'quantity': line.get_quantity()}
        form = ReplaceCartLineForm(data, cart=cart, product=line.product,
                                   initial=initial)
        line.form = form
        if form.is_valid():
            form.save()
            if request.is_ajax():
                response = {
                    'productId': line.product.pk,
                    'subtotal': currencyfmt(
                        line.get_total().gross,
                        line.get_total().currency),
                    'total': 0}
                if cart:
                    response['total'] = currencyfmt(
                        cart.get_total().gross, cart.get_total().currency)
                return JsonResponse(response)
            return redirect('cart:index')
        elif data is not None:
            if request.is_ajax():
                response = {'error': form.errors}
                return JsonResponse(response, status=400)
    return TemplateResponse(
        request, 'cart/index.html', {
            'cart': cart})

templates/cart/index.html
{% extends "base.html" %}
{% load gross from prices_i18n %}
{% load i18n %}
{% load static from staticfiles %}
{% load render_bundle from webpack_loader %}

{% block title %}{% trans "Your cart" %} — {{ block.super }}{% endblock %}

{% block breadcrumb %}
    {{ block.super }}
<li><a href="{% url 'cart:index' %}">{% trans "Cart" %}</a></li>
{% endblock breadcrumb %}

{% block stylesheet %}
  {{ block.super }}
  {% render_bundle 'cart' 'css' %}
{% endblock stylesheet %}

{% block footer_scripts %}
  {{ block.super }}
  {% render_bundle 'cart' 'js' %}
{% endblock footer_scripts %}

{% block content %}
{% if cart %}
    <table class="table table-striped cart" id="cart-items">
        <thead>
        <tr>
            <th class="col-xs-5 col-sm-2 col-md-1">{% trans "Product" %}</th>
            <th class="col-sm-5 hidden-xs"></th>
            <th class="col-xs-6 col-sm-3 col-md-2">{% trans "Quantity" %}</th>
            <th class="col-sm-1 hidden-xs text-right">{% trans "Price" %}</th>
            <th class="col-xs-1 text-right">{% trans "Subtotal" %}</th>
        </tr>
        </thead>
        <tfoot>
        <tr>
            <td class="hidden-xs" colspan="2"></td>
            <td class="col-xs-9 col-md-9 text-right lead" colspan="2">{% trans "Total" %}:
            <td class="col-xs-3 col-md-2 text-right lead"><b class="cart-total">{{ cart.get_total }}</b></td>
        </tr>
        </tfoot>
        <tbody>
            {% for line in cart %}
                <tr class="cart-item">
                    <td class="hidden-xs">
                        <a href="{{ line.product.get_absolute_url }}">
                            {% if line.product.product.images.first %}
                                <img class="cart-item-image" itemprop="image" src="{{ line.product.product.images.first.image.crop.100x100 }}" alt="">
                            {% else %}
                                <img class="cart-item-image" src="{% static 'images/product-image-placeholder-small.png' %}" alt="">
                            {% endif %}
                        </a>
                    </td>
                    <td>
                        <a href="{{ line.product.get_absolute_url }}">
                            {{ line.product.product }} - {{ line.product.display_variant }}
                        </a>
                    </td>
                    <td>
                        <div class="cart-item-amount">
                            <form role="form" action="{% url "cart:update_line" product_id=line.product.pk %}" method="post" class="form-cart">
                                <div class="input-group cart-item-quantity js-hidden{% if line.form.quantity.errors %} has-error{% endif %}">
                                    {{ line.form.quantity }}
                                    <span class="input-group-btn">
                                        <button class="btn btn-info" type="submit">{% trans "Update" %}</button>
                                    </span>
                                </div>
                                {% if line.form.quantity.errors %}
                                    {% for error in line.form.quantity.errors %}
                                        <span class="text-danger">{{ error }}</span>
                                    {% endfor %}
                                {% endif %}
                                {% csrf_token %}
                            </form>

                            <button type="submit" class="btn btn-link btn-sm cart-item-remove">
                                <span class="text-muted">{% trans "Remove from cart" %}</span>
                            </button>
                        </div>
                    </td>
                    <td class="text-right hidden-xs">{{ line.product.price }}</td>
                    <td class="text-right cart-item-subtotal" data-product-id="{{ line.product.pk }}">
                        {{ line.get_total }}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="form-group">
        <div>
            <a href="{% url "checkout:index" %}" class="btn btn-primary btn-lg pull-right">{% trans "Proceed to checkout" %}</a>
        </div>
    </div>
{% else %}
<p>
    {% trans 'Your cart is empty' %}
</p>
{% endif %}
{% endblock content %}