ecommerce/order/urls.py
from django.conf.urls import url

from ..core import TOKEN_PATTERN
from . import views


urlpatterns = [
    url(r'^%s/$' % (TOKEN_PATTERN,), views.details, name='details'),
    url(r'^%s/payment/$' % (TOKEN_PATTERN,),
        views.payment, name='payment'),
    url(r'^%s/payment/(?P<variant>[-\w]+)/$' % (TOKEN_PATTERN,),
        views.start_payment, name='payment'),
    url(r'^%s/cancel-payment/$' % (TOKEN_PATTERN,), views.cancel_payment,
        name='cancel-payment')
]

ecommerce/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.contrib.staticfiles.views import serve

from .cart.urls import urlpatterns as cart_urls
from .checkout.urls import urlpatterns as checkout_urls
from .core.sitemaps import sitemaps
from .core.urls import urlpatterns as core_urls
from .order.urls import urlpatterns as order_urls
from .product.urls import urlpatterns as product_urls
from .userprofile.urls import urlpatterns as userprofile_urls


admin.autodiscover()

urlpatterns = [
    url(r'^', include(core_urls)),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^cart/', include(cart_urls, namespace='cart')),
    url(r'^checkout/', include(checkout_urls, namespace='checkout')),
    url(r'^order/', include(order_urls, namespace='order')),
    url(r'^products/', include(product_urls, namespace='product')),
    url(r'^profile/', include(userprofile_urls, namespace='profile')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'),
    url(r'^api/v1/', include('ecommerce.urls_api')),
    url(r'', include('payments.urls'))
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', serve)
    ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/order/models.py
from __future__ import unicode_literals

from decimal import Decimal
from uuid import uuid4

import emailit.api
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils.encoding import python_2_unicode_compatible, smart_text
from django.utils.timezone import now
from django.utils.translation import pgettext_lazy
from payments import PurchasedItem
from payments.models import BasePayment
from prices import Price, FixedDiscount
from satchless.item import ItemLine, ItemSet

from ..core.utils import build_absolute_uri
from ..discount.models import Voucher
from ..product.models import Product, Stock
from ..userprofile.models import Address
from . import Status


class OrderManager(models.Manager):

    def recalculate_order(self, order):
        prices = [group.get_total() for group in order
                  if group.status != Status.CANCELLED]
        total_net = sum(p.net for p in prices)
        total_gross = sum(p.gross for p in prices)
        shipping = [group.shipping_price for group in order]
        if shipping:
            total_shipping = sum(shipping[1:], shipping[0])
        else:
            total_shipping = Price(0, currency=settings.DEFAULT_CURRENCY)
        total = Price(net=total_net, gross=total_gross,
                      currency=settings.DEFAULT_CURRENCY)
        total += total_shipping
        order.total = total
        order.save()


@python_2_unicode_compatible
class Order(models.Model, ItemSet):
    status = models.CharField(
        pgettext_lazy('Order field', 'order status'),
        max_length=32, choices=Status.CHOICES, default=Status.NEW)
    created = models.DateTimeField(
        pgettext_lazy('Order field', 'created'),
        default=now, editable=False)
    last_status_change = models.DateTimeField(
        pgettext_lazy('Order field', 'last status change'),
        default=now, editable=False)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, blank=True, null=True, related_name='orders',
        verbose_name=pgettext_lazy('Order field', 'user'))
    tracking_client_id = models.CharField(
        max_length=36, blank=True, editable=False)
    billing_address = models.ForeignKey(
        Address, related_name='+', editable=False)
    shipping_address = models.ForeignKey(
        Address, related_name='+', editable=False, null=True)
    anonymous_user_email = models.EmailField(
        blank=True, default='', editable=False)
    token = models.CharField(
        pgettext_lazy('Order field', 'token'), max_length=36, unique=True)
    total_net = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    total_tax = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    voucher = models.ForeignKey(
        Voucher, null=True, related_name='+', on_delete=models.SET_NULL)
    discount_amount = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True)
    discount_name = models.CharField(max_length=255, default='', blank=True)

    objects = OrderManager()

    class Meta:
        ordering = ('-last_status_change',)

    def save(self, *args, **kwargs):
        if not self.token:
            self.token = str(uuid4())
        return super(Order, self).save(*args, **kwargs)

    def change_status(self, status):
        if status != self.status:
            self.status = status
            self.save()
            self.history.create(status=status)

    def get_items(self):
        return OrderedItem.objects.filter(delivery_group__order=self)

    def is_fully_paid(self):
        total_paid = sum([payment.total for payment in
                          self.payments.filter(status='confirmed')], Decimal())
        total = self.get_total()
        return total_paid >= total.gross

    def get_user_email(self):
        if self.user:
            return self.user.email
        return self.anonymous_user_email

    def __iter__(self):
        return iter(self.groups.all())

    def __repr__(self):
        return '<Order #%r>' % (self.id,)

    def __str__(self):
        return '#%d' % (self.id, )

    @property
    def discount(self):
        return FixedDiscount(
            amount=self.discount_amount, name=self.discount_name)

    def get_total(self):
        return self.total

    @property
    def billing_full_name(self):
        return '%s %s' % (self.billing_first_name, self.billing_last_name)

    def get_absolute_url(self):
        return reverse('order:details', kwargs={'token': self.token})

    def get_delivery_total(self):
        return sum([group.shipping_price for group in self.groups.all()],
                   Price(0, currency=settings.DEFAULT_CURRENCY))

    def send_confirmation_email(self):
        email = self.get_user_email()
        payment_url = build_absolute_uri(
            reverse('order:details', kwargs={'token': self.token}))
        context = {'payment_url': payment_url}

        emailit.api.send_mail(email, context, 'order/emails/confirm_email')

    def get_last_payment_status(self):
        last_payment = self.payments.last()
        if last_payment:
            return last_payment.status

    def get_last_payment_status_display(self):
        last_payment = self.payments.last()
        if last_payment:
            return last_payment.get_status_display()

    def is_pre_authorized(self):
        return self.payments.filter(status='preauth').exists()

    def create_history_entry(self, comment='', status=None, user=None):
        if not status:
            status = self.status
        self.history.create(status=status, comment=comment, user=user)

    def is_shipping_required(self):
        return any(group.is_shipping_required() for group in self.groups.all())

    @property
    def total(self):
        if self.total_net is not None:
            gross = self.total_net.net + self.total_tax.gross
            return Price(net=self.total_net.net, gross=gross,
                         currency=settings.DEFAULT_CURRENCY)

    @total.setter
    def total(self, price):
        self.total_net = price
        self.total_tax = Price(price.tax, currency=price.currency)

    def get_subtotal_without_voucher(self):
        if self.get_items():
            return super(Order, self).get_total()
        return Price(net=0, currency=settings.DEFAULT_CURRENCY)

    def get_total_shipping(self):
        costs = [group.shipping_price for group in self]
        if costs:
            return sum(costs[1:], costs[0])
        return Price(net=0, currency=settings.DEFAULT_CURRENCY)

    def can_cancel(self):
        return self.status not in {Status.CANCELLED, Status.SHIPPED}


class DeliveryGroup(models.Model, ItemSet):
    status = models.CharField(
        pgettext_lazy('Delivery group field', 'delivery status'),
        max_length=32, default=Status.NEW, choices=Status.CHOICES)
    order = models.ForeignKey(Order, related_name='groups', editable=False)
    shipping_price = models.DecimalField(max_digits=12, decimal_places=2, null=True, blank=True, default=0)
    shipping_method_name = models.CharField(
        max_length=255, null=True, default=None, blank=True, editable=False)
    tracking_number = models.CharField(max_length=255, default='', blank=True)
    last_updated = models.DateTimeField(null=True, auto_now=True)

    def __str__(self):
        return pgettext_lazy(
            'Delivery group str', 'Shipment #%s') % self.pk

    def __repr__(self):
        return '%s(%r)' % (self.__class__.__name__, list(self))

    def __iter__(self):
        if self.id:
            return iter(self.items.all())
        return super(DeliveryGroup, self).__iter__()

    @property
    def shipping_required(self):
        return self.shipping_method_name is not None

    def change_status(self, status):
        self.status = status
        self.save()

    def get_total(self, **kwargs):
        subtotal = super(DeliveryGroup, self).get_total(**kwargs)
        return subtotal + self.shipping_price

    def add_items_from_partition(self, partition):
        for item_line in partition:
            product_variant = item_line.product
            price = item_line.get_price_per_item()
            quantity = item_line.get_quantity()
            stock = product_variant.select_stockrecord(quantity)
            self.items.create(
                product=product_variant.product,
                quantity=quantity,
                unit_price_net=price.net,
                product_name=smart_text(product_variant),
                product_sku=product_variant.sku,
                unit_price_gross=price.gross,
                stock=stock,
                stock_location=stock.location if stock else None)
            if stock:
                # allocate quantity to avoid overselling
                Stock.objects.allocate_stock(stock, quantity)

    def get_total_quantity(self):
        return sum([item.get_quantity() for item in self])

    def is_shipping_required(self):
        return self.shipping_required

    def can_ship(self):
        return self.is_shipping_required() and self.status == 'new'

    def can_cancel(self):
        return self.status != Status.CANCELLED


class OrderedItemManager(models.Manager):

    def move_to_group(self, item, target_group, quantity):
        try:
            target_item = target_group.items.get(
                product=item.product, product_name=item.product_name,
                product_sku=item.product_sku)
        except ObjectDoesNotExist:
            target_group.items.create(
                delivery_group=target_group, product=item.product,
                product_name=item.product_name, product_sku=item.product_sku,
                quantity=quantity, unit_price_net=item.unit_price_net,
                stock=item.stock,
                unit_price_gross=item.unit_price_gross)
        else:

ecommerce/order/views.py
import logging

from django.conf import settings
from django.contrib import messages
from django.db import transaction
from django.http import Http404, HttpResponseForbidden
from django.shortcuts import get_object_or_404, redirect
from django.utils.translation import ugettext as _
from django.template.response import TemplateResponse
from payments import RedirectNeeded

from .forms import PaymentDeleteForm, PaymentMethodsForm
from .models import Order, Payment
from .utils import check_order_status, get_ip

logger = logging.getLogger(__name__)


def details(request, token):
    orders = Order.objects.prefetch_related('groups__items')
    order = get_object_or_404(orders, token=token)
    groups = order.groups.all()
    return TemplateResponse(request, 'order/details.html',
                            {'order': order, 'groups': groups})


def payment(request, token):
    orders = Order.objects.prefetch_related('groups__items')
    order = get_object_or_404(orders, token=token)
    groups = order.groups.all()
    payments = order.payments.all()
    form_data = request.POST or None
    try:
        waiting_payment = order.payments.get(status='waiting')
    except Payment.DoesNotExist:
        waiting_payment = None
        waiting_payment_form = None
    else:
        form_data = None
        waiting_payment_form = PaymentDeleteForm(
            None, order=order, initial={'payment_id': waiting_payment.id})
    if order.is_fully_paid():
        form_data = None
    payment_form = None
    if not order.is_pre_authorized():
        payment_form = PaymentMethodsForm(form_data)
        # FIXME: redirect if there is only one payment method
        if payment_form.is_valid():
            payment_method = payment_form.cleaned_data['method']
            return redirect('order:payment', token=order.token,
                            variant=payment_method)
    return TemplateResponse(request, 'order/payment.html',
                            {'order': order, 'groups': groups,
                             'payment_form': payment_form,
                             'waiting_payment': waiting_payment,
                             'waiting_payment_form': waiting_payment_form,
                             'payments': payments})


@check_order_status
def start_payment(request, order, variant):
    waiting_payments = order.payments.filter(status='waiting').exists()
    if waiting_payments:
        return redirect('order:payment', token=order.token)
    billing = order.billing_address
    total = order.get_total()
    defaults = {'total': total.gross,
                'tax': total.tax, 'currency': total.currency,
                'delivery': order.get_delivery_total().gross,
                'billing_first_name': billing.first_name,
                'billing_last_name': billing.last_name,
                'billing_address_1': billing.street_address_1,
                'billing_address_2': billing.street_address_2,
                'billing_city': billing.city,
                'billing_postcode': billing.postal_code,
                'billing_country_code': billing.country,
                'billing_email': order.get_user_email(),
                'description': _('Order %(order_number)s') % {
                    'order_number': order},
                'billing_country_area': billing.country_area,
                'customer_ip_address': get_ip(request)}
    variant_choices = settings.CHECKOUT_PAYMENT_CHOICES
    if variant not in [code for code, dummy_name in variant_choices]:
        raise Http404('%r is not a valid payment variant' % (variant,))
    with transaction.atomic():
        order.change_status('payment-pending')
        payment, dummy_created = Payment.objects.get_or_create(
            variant=variant, status='waiting', order=order, defaults=defaults)
        try:
            form = payment.get_form(data=request.POST or None)
        except RedirectNeeded as redirect_to:
            return redirect(str(redirect_to))
        except Exception:
            logger.exception('Error communicating with the payment gateway')
            messages.error(
                request,
                _('Oops, it looks like we were unable to contact the selected'
                  ' payment service'))
            payment.change_status('error')
            return redirect('order:payment', token=order.token)
    template = 'order/payment/%s.html' % variant
    return TemplateResponse(request, [template, 'order/payment/default.html'],
                            {'form': form, 'payment': payment})


@check_order_status
def cancel_payment(request, order):
    form = PaymentDeleteForm(request.POST or None, order=order)
    if form.is_valid():
        with transaction.atomic():
            form.save()
        return redirect('order:payment', token=order.token)
    return HttpResponseForbidden()

templates/order/details.html
{% extends "base.html" %}

{% load gross from prices_i18n %}
{% load i18n %}
{% load staticfiles %}
{% load discount_amount_for from prices %}

{% block title %}{% trans "Order" %} {{ order }} — {{ block.super }}{% endblock %}

{% block outerbreadcrumb %}
    {% if order.user == user %}
    <ul class="breadcrumb" itemprop="breadcrumb">
        <li><a href="/">{% trans "Home" %}</a></li>
        <li><a href="{% url 'profile:orders' %}">{% trans "Your orders" %}</a></li>
        <li><a href="{% url 'order:details' token=order.token %}">{{ order }}</a></li>
    </ul>
    {% endif %}
{% endblock outerbreadcrumb %}

{% block content %}
    {# This view is available by just knowing url,          #}
    {# so we don't show all details (like delivery address) #}
    {# unless current user is owner of the order.           #}

    <div class="row">
        <div class="col-sm-12">
            <h3 class="page-header page-header--order">
                <span class="text-muted">{% blocktrans %}Order {{ order }}: {% endblocktrans %}</span>
                {{ order.get_status_display }}

                {% if not order.is_fully_paid %}
                    {% if order.is_pre_authorized %}
                        <a href="{% url "order:payment" token=order.token %}" class="btn btn-info">{% trans "Payment details" %}</a>
                    {% else %}
                        <a href="{% url "order:payment" token=order.token %}" class="btn btn-primary">{% trans "Pay for order" %}</a>
                    {% endif %}
                {% endif %}
            </h3>
        </div>
    </div>

    <div class="row">
        {% if order.user == user %}
            <div class="col-sm-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        {% trans "Billing address" %}
                    </div>
                    <div class="panel-body">
                        <address>{% include "userprofile/snippets/address-details.html" with address=order.billing_address %}</address>
                    </div>
                </div>
            </div>
            {% if order.is_shipping_required %}
                <div class="col-sm-6">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            {% trans "Shipping address" %}
                        </div>
                        <div class="panel-body">
                            <address>{% include "userprofile/snippets/address-details.html" with address=order.shipping_address %}</address>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endif %}
    </div>

    {% for group in groups %}
        <div class="panel panel-default">
            <div class="panel-heading">
                {% blocktrans with number=forloop.counter %}Shipment #{{ number }}{% endblocktrans %}
                <span class="pull-right">
                    <span class="label label-default">{{ group.get_status_display }}</span>
                </span>
            </div>
            <table class="table">
                <thead>
                    <tr>
                        <th class="col-sm-6">{% trans "Name" %}</th>
                        <th class="col-sm-3 text-right">{% trans "Price" %}</th>
                        <th class="col-sm-3 text-right">{% trans "Subtotal" %}</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th colspan="2">{% trans "Total" %}</th>
                        <th class="text-right">{% gross group.get_total %}</th>
                    </tr>
                </tfoot>
                <tbody>
                    {% for item in group %}
                        <tr>
                            <td>{{ item.product }}{% if item.quantity != 1 %} <em>×{{ item.quantity }}</em>{% endif %}</td>
                            <td class="text-right">{% gross item.get_price_per_item %}</td>
                            <td class="text-right">{% gross item.get_total %}</td>
                        </tr>
                    {% endfor %}
                    {% if group.shipping_price.gross %}
                        <tr>
                            <td class="col-sm-4">
                                {% trans "Shipping" %}
                            </td>
                            <td class="text-right">{% gross group.shipping_price %}</td>
                            <td class="text-right">{% gross group.shipping_price %}</td>
                        </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    {% endfor %}
    {% if order.discount_amount %}
        <div class="panel panel-default">
            <div class="panel-heading">
                {{ order.discount_name }}
            </div>
            <div class="panel-body text-right">
                <strong>{% gross order.discount|discount_amount_for:order.total %}</strong>
            </div>
        </div>
    {% endif %}
    {% if order.discount_amount or groups|length > 1 %}
        <div class="panel panel-default">
            <div class="panel-heading">
                {% trans "Total" %}
            </div>
            <div class="panel-body text-right">
                <strong>{% gross order.total %}</strong>
            </div>
        </div>
    {% endif %}
{% endblock content %}

templates/order/payment.html
{% extends "base.html" %}

{% load bootstrap_form from bootstrap3 %}
{% load gross from prices_i18n %}
{% load discount_amount_for from prices %}
{% load i18n %}
{% load staticfiles %}

{% block title %}{% trans "Pay for order" %} {{ order }} — {{ block.super }}{% endblock %}

{% block outerbreadcrumb %}
    {% if order.user == user %}
    <ul class="breadcrumb" itemprop="breadcrumb">
        <li><a href="/">{% trans "Home" %}</a></li>
        <li><a href="{% url 'profile:orders' %}">{% trans "Your orders" %}</a></li>
        <li><a href="{% url 'order:details' token=order.token %}">{{ order }}</a></li>
    </ul>
    {% endif %}
{% endblock outerbreadcrumb %}

{% block content %}
    <div class="row">
        <div class="col-sm-8">
            {% if order.user == user or not order.is_fully_paid %}
                {% if not order.is_fully_paid %}
                    <div class="panel panel-info">
                        {% if waiting_payment %}
                            <div class="panel-heading">
                                {% trans "Payment pending" %}
                            </div>
                            <div class="panel-body">
                                <form method="post" action="{% url 'order:cancel-payment' token=order.token %}">
                                    {% csrf_token %}
                                    <p>{% trans "We are currently waiting for an external service to authorize your payment for this order." %}</p>
                                    <p>{% trans "Current status" %}: <span class="label label-default">{{ waiting_payment.get_status_display }}</span></p>
                                    <p>{% trans "Unless you are absolutely sure that the process will not complete (for example you have closed the browser window before paying), you should wait before attempting a new payment. Please be warned that if you try again and the previous transaction succeeds you might end up being charged twice." %}</p>
                                    {% bootstrap_form waiting_payment_form %}
                                    <button type="submit" class="btn btn-danger">{% trans "I understand, allow me to pay again" %}</button>
                                </form>
                            </div>
                        {% elif payment_form %}
                            <div class="panel-heading">
                                {% trans "Pay for order" %} {{ order }}
                            </div>
                            <div class="panel-body">
                                <form method="post" action="{% url "order:payment" token=order.token %}">
                                    {% csrf_token %}
                                    {{ payment_form }}
                                    <div class="form-group text-right">
                                        {% block form_submit %}
                                            <button type="submit" class="btn btn-primary">
                                                {% trans "Proceed to payment" %}
                                            </button>
                                        {% endblock %}
                                    </div>
                                </form>
                            </div>
                        {% else %}
                            <div class="panel-body alert-info">
                                <span>{% trans "You've authorized transaction. Order is in processing" %}</span>
                            </div>
                        {% endif %}
                    </div>
                {% endif %}
            {% endif %}
        </div>
    </div>

    <div class="row">
        {% if order.user == user %}
            <div class="col-sm-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        {% trans "Billing address" %}
                    </div>
                    <div class="panel-body">
                        <address>{% include "userprofile/snippets/address-details.html" with address=order.billing_address %}</address>
                    </div>
                </div>
            </div>

            <div class="col-sm-6">
                {% if order.is_shipping_required %}
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            {% trans "Shipping address" %}
                        </div>
                        <div class="panel-body">
                            <address>{% include "userprofile/snippets/address-details.html" with address=order.shipping_address %}</address>
                        </div>
                    </div>
                {% endif %}
            </div>
        {% endif %}
    </div>

    {% for group in groups %}
        <div class="panel panel-default">
            <div class="panel-heading">
                {% blocktrans with number=forloop.counter %}Shipment #{{ number }}{% endblocktrans %}
            </div>
            <table class="table">
                <thead>
                    <tr>
                        <th class="col-sm-6">{% trans "Name" %}</th>
                        <th class="col-sm-3 text-right">{% trans "Price" %}</th>
                        <th class="col-sm-3 text-right">{% trans "Subtotal" %}</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th colspan="2">{% trans "Total" %}</th>
                        <th class="text-right">{% gross group.get_total %}</th>
                    </tr>
                </tfoot>
                <tbody>
                    {% for item in group %}
                        <tr>
                            <td>{{ item.product }}{% if item.quantity != 1 %} <em>×{{ item.quantity }}</em>{% endif %}</td>
                            <td class="text-right">{% gross item.get_price_per_item %}</td>
                            <td class="text-right">{% gross item.get_total %}</td>
                        </tr>
                    {% endfor %}
                    {% if group.shipping_price.gross %}
                        <tr>
                            <td class="col-sm-4">
                                {% trans "Shipping" %}
                            </td>
                            <td class="text-right">{% gross group.shipping_price %}</td>
                            <td class="text-right">{% gross group.shipping_price %}</td>
                        </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
    {% endfor %}
    {% if order.discount_amount %}
        <div class="panel panel-default">
            <div class="panel-heading">
                {{ order.discount_name }}
            </div>
            <div class="panel-body text-right">
                <strong>{% gross order.discount|discount_amount_for:order.total %}</strong>
            </div>
        </div>
    {% endif %}
    {% if order.discount_amount or groups|length > 1 %}
        <div class="panel panel-default">
            <div class="panel-heading">
                {% trans "Total" %}
            </div>
            <div class="panel-body text-right">
                <strong>{% gross order.total %}</strong>
            </div>
        </div>
    {% endif %}
{% endblock content %}

templates/order/success.html
{% extends "base.html" %}
{% load gross from prices_i18n %}
{% load i18n %}

{% block title %}{% trans "Order complete!" %} — {{ block.super }}{% endblock %}


{% block content %}
<h2>{% trans "Your order is now complete" %}</h2>
<p>{% trans "Thank you for your purchase!" %}</p>

<p>{% trans "Your order number is" %}: <a href="{% url 'order:details' token=order.token %}">{{ order }}</a></p>
{% endblock content %}

{% block google-analytics-script %}
    {{ block.super }}
    __ga('require', 'ecommerce', 'ecommerce.js');
    __ga('set', 'currencyCode', '{{ DEFAULT_CURRENCY }}');
    __ga('ecommerce:addTransaction', {
      'id': '{{ order.id }}',
      'affiliation': 'Saleor',
      'revenue': '{{ order.get_total.gross }}',
      'shipping': '{{ order.get_delivery_total.gross }}',
      'tax': '{{ order.get_total.tax }}'
    });
    {% for item in order.get_items %}
     __ga('ecommerce:addItem', {
        'id': '{{ item.id }}',
        'name': '{{ item }}',
        'sku': '{{ item.sku }}',
        'category': '{{ item.product.category }}',
        'price': '{{ item.unit_price_gross }}',
        'quantity': '{{ item.quantity }}'
      });
    {% endfor %}
    __ga('ecommerce:send');
{% endblock google-analytics-script %}